language: haxe

os:
  - linux

haxe:
  - "3.4.0-rc.2"
  - development

matrix:
  allow_failures:
    - haxe: development

script:
  - haxelib git electron https://github.com/tong/hxelectron
  - haxe run.hxml
  - neko run.n
  - haxe doc.hxml
  - haxe --cwd demo build.hxml
